---
output: html_document
---

<style type="text/css">
.navbar-header  {
    margin-left: -160px !important;
}
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

******
### COVID data sources 
******

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(DT)

dat <- read_csv(here("data/Data.csv"))
```

```{r}
dat_html <- dat %>%
  filter(!is.na("Dataset")) %>%
  mutate(`Data Source` =  paste0("<a href='", Links,"'>",`Dataset`,"</a>")) %>%
  mutate(API = if_else(API == 1, "Yes", "No"), 
         `Date added` = as.factor(`Date added on Mathematica's website`)) %>%
  select(-Description, -Dataset, -Links, -`Date added on Mathematica's website`, 
         `Update freq/date` = `Update frequency/date`,
         `Case and testing counts` = `Case count and testing rates`, 
         `Diagnosis codes` = `Covid-19 diagnosis codes`, 
         `Capacity and needs` = `Provider capacity and patient needs`, 
         `Identifying at-risk pops.` = `Identifying at-risk populations`, 
         `Policy and legislative actions` = `Policy and legislative actions to curb transmission`, 
         `Other` = `Guidance documents and other resources`) %>%
  select(`Data Source`, everything()) %>% 
  replace(is.na(.), "-")

DT::datatable(dat_html, filter = "top", escape = FALSE, 
              options = list(
                autoWidth = TRUE,
                columnDefs = list(list(width = '12px', targets = "_all")),
                pageLength = 5, 
                lengthMenu = c(5, 10, 20), 
                initComplete = JS("function(settings, json) {",
                                  "$(this.api().table().header()).css({'font-size': '12px', 'background-color': '#2c3c54', 'color': '#fff'});",
                                  "}"))) %>%  
  formatStyle(columns = colnames(.$x$data), `font-size` = '12px')
```