---
output: html_document
---

<style type="text/css">
.navbar-header  {
    margin-left: -160px !important;
}
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


******
### COVID resources
******

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(DT)

agg <- read_csv(here("data/Aggregates.csv"))
```

```{r}
agg_html <- agg %>%
  mutate(Category = as.factor(`Website Category`),
         `Date added` = as.factor(`Date posted on Mathematica's website`)) %>%
  mutate_all(function(x){gsub('[^ -~]', '', x)}) %>%
  select(`Source name`, Category, Description = `Description of contents`, `Date added`)

DT::datatable(agg_html, filter = "top", escape = FALSE,
              options = list(
                autowidth = T,
                columnDefs = list(list(width = '12px', targets = "_all")),
                pageLength = 5, 
                lengthMenu = c(5, 10, 20), 
                initComplete = JS("function(settings, json) {",
                                  "$(this.api().table().header()).css({'font-size': '12px', 'background-color': '#2c3c54', 'color': '#fff'});",
                                  "}"))) %>%  
  formatStyle(columns = colnames(.$x$data), `font-size` = '12px')
```